server:
  port: 8666
  servlet:
    context-path: /tiafs/
    session:
      cookie:
        name: JSESSIONID
        max-age: 86400 #24h
        path: / #所有路径都携带cookie至服务器
        http-only: false #设置为true 则cookie将不能被JS读取
#        secure: true #cookie仅允许用https传输

spring:
  application:
    name: teacher-annual-info-report-system


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cw_tiafs?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    url: jdbc:mysql://47.93.19.130:3306/cw_tiafs?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
  redis:
    host: 47.93.19.130
    port: 6379
    #password: xveacw8023
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8000/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}

mybatis:
  mapper-locations: classpath*:mapper/*.xml

jwt:
  encrypt-secret: 4A614E645267556B58703273357638792F423F45284-2D4A6Z-6A586E32723-2B4D6-472D4BCD #秘钥
  timestamp-key: tempstamp #时间戳
  location: cookie #cookie
  max-age: 86400 #过期时间 24h

token:
  cookie-name: token
  header-name: Authorization
  parameter-name: token
